### ISSUE TITLE
correct header in opencv-import.hpp

### ISSUE THREAD

**Issue by dsxmachina** [relrotciv/vxa#1]
Hello,

the file opencv-import.hpp tries to include <opencv2/cv.hpp>,
which is an old header file, that is not present in current opencv versions.

If you replace it with 
`#include <opencv2/opencv.hpp>` 

everything works just fine.

Thank you for that library btw. - great work!

**Comment by relrotciv** [comment]
Hi, thanks for your kind words and for the bug report! This is fixed in master 35e03ae. Thanks, Victor
